CREATE DATABASE DESAFIO;

CREATE TABLE POKEMON
(
    ID      INT PRIMARY KEY,
    NAME    VARCHAR(255),
    HEIGHT  INTEGER,
    WEIGHT  INTEGER,
    TEAM_ID INT,
    FOREIGN KEY (TEAM_ID) REFERENCES TEAM (ID)
);

CREATE TABLE TEAM
(
    ID    INTEGER PRIMARY KEY,
    NAME  VARCHAR(255) UNIQUE,
    OWNER VARCHAR(255)
);

CREATE SEQUENCE DESAFIO.SQ_TEAM INCREMENT BY 1;
CREATE SEQUENCE DESAFIO.SQ_POKEMON INCREMENT BY 1;
